name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=22.3.1
  - mlflow=2.0.1
  - scikit-learn=0.24.1
  - matplotlib=3.6.2
  - pillow=9.4.0
  - pip:
      - wandb==0.10.21
